CREATE TABLE user (
  id INT AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  nickname VARCHAR(50) NOT NULL,
  hased_password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
)

CREATE TABLE social_account (
  id INT AUTO_INCREMENT,
  provider VARCHAR(50) NOT NULL,
  provider_id VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  UNIQUE (provider_id, user_id)
)

CREATE TABLE product (
  id INT AUTO_INCREMENT,
  title VARCHAR(10) NOT NULL,
  description TEXT NOT NULL,
  price INT NOT NULL,
  image_url TEXT,
  user_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
)

CREATE TABLE tag (
  id INT AUTO_INCREMENT,
  tag VARCHAR (5) NOT NULL,
  PRIMARY KEY(id)
)

CREATE TABLE product_tag (
  tag_id INT NOT NULL,
  product_id INT NOT NULL,
  PRIMARY KEY(tag_id, product_id),
  FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
)

CREATE TABLE product_comment (
  id INT AUTO_INCREMENT,
  comment VARCHAR(255),
  user_id INT NOT NULL, 
  product_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
)

CREATE TABLE product_like (
  user_id INT NOT NULL, 
  product_id INT NOT NULL, 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (user_id, product_id), 
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, 
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE article (
  id INT AUTO_INCREMENT,
  title VARCHAR(10) NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  user_id INT NOT NULL, 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
)

CREATE TABLE article_comment (
  id INT AUTO_INCREMENT,
  comment VARCHAR(255),
  article_id INT NOT NULL,
  user_id INT NOT NULL, 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE
)

CREATE TABLE article_like (
  user_id INT NOT NULL, 
  article_id INT NOT NULL, 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (user_id, article_id), 
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, 
  FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE
);