export enum BusinessExceptionType {
  INVALID_REQUEST,
  REFRESHTOKEN_FORM,
  NAME_TOO_LONG,
  DESCRIPTION_TOO_SHORT,
  PRICE_NOT_NEGATIVE_NUMBER,
  LEAST_ONE_TAG,
  SORT_FORM,
  LIMIT_MAX_20,
  TITLE_TOO_LONG,
  CONTENT_TOO_SHORT,
  PASSWORD_MISMATCH,
  TOKEN_EXPIRED,
  INVALID_AUTH,
  REFRESHTOKEN_MISMATCH,
  EMAIL_TOO_LONG,
  PASSWORD_TOO_SHORT,
  NICKNAME_TOO_LONG,
  ZOD_FORM,
  NAME_NOT_EXIST,
  DESCRIPTION_NOT_EXIST,
  PRICE_NOT_EXIST,
  TAGS_NOT_EXIST,
  TITLE_NOT_EXIST,
  CONTENT_NOT_EXIST,
  ARTICLE_NOT_EXIST,
  COMMENT_NOT_EXIST,
  PRODUCT_NOT_EXIST,
  NOTIFICATION_NOT_EXIST,
  LIKE_NOT_EXIST,
  LIKE_EXIST,
  ID_NOT_EXIST,
  TARGETTYPE_NOT_EXIST,
  USER_NOT_EXIST,
  USER_PRODUCTS_NOT_EXIST,
  USER_LIKEPRODUCTS_NOT_EXIST,
  USER_LIKEARTICLES_NOT_EXIST,
  REFRESHTOKEN_NOT_EXIST,
  USERID_NOT_EXIST,
  PRODUCT_ALREADY_EXIST,
  ARTICLE_ALREADY_EXIST,
  COMMENT_ALREADY_EXIST,
  EMAIL_DUPLICATE,
  FOREIGN_KEY_VIOLATION,
  USER_EXIST,
  UNAUTHORIZED_PRODUCT_OWNER,
  UNAUTHORIZED_ARTICLE_OWNER,
  UNAUTHORIZED_COMMENT_OWNER,
  CORS_ORIGIN_NOT_ALLOWED,
  INVALID_TOKEN,
  NOT_PATH,
}

export const BusinessExceptionTable: Record<
  BusinessExceptionType,
  { statusCode: number; message: string }
> = {
  [BusinessExceptionType.INVALID_REQUEST]: { statusCode: 400, message: "잘못된 요청입니다." },
  [BusinessExceptionType.REFRESHTOKEN_FORM]: { statusCode: 400, message: "refresh 토큰 양식에 안 맞습니다." },
  [BusinessExceptionType.NAME_TOO_LONG]: { statusCode: 422, message: "이름의 최대 길이는 20글자입니다." },
  [BusinessExceptionType.DESCRIPTION_TOO_SHORT]: { statusCode: 422, message: "설명이 너무 짧습니다.(최소 6글자)" },
  [BusinessExceptionType.PRICE_NOT_NEGATIVE_NUMBER]: { statusCode: 422, message: "숫자는 양의 정수만 가능합니다." },
  [BusinessExceptionType.LEAST_ONE_TAG]: { statusCode: 422, message: "최소 1개 이상 넣어야 합니다." },
  [BusinessExceptionType.SORT_FORM]: { statusCode: 400, message: "정렬 양식이 안 맞습니다." },
  [BusinessExceptionType.LIMIT_MAX_20]: { statusCode: 422, message: "limit 최대치는 20입니다." },
  [BusinessExceptionType.TITLE_TOO_LONG]: { statusCode: 422, message: "제목의 최대 길이는 20글자입니다." },
  [BusinessExceptionType.CONTENT_TOO_SHORT]: { statusCode: 422, message: "내용이 너무 짧습니다.(최소 6글자)" },
  [BusinessExceptionType.PASSWORD_MISMATCH]: { statusCode: 401, message: "비밀번호가 일치하지 않습니다." },
  [BusinessExceptionType.TOKEN_EXPIRED]: { statusCode: 401, message: "토큰이 만료됐습니다." },
  [BusinessExceptionType.INVALID_AUTH]: { statusCode: 401, message: "인증이 유효하지 않습니다." },
  [BusinessExceptionType.REFRESHTOKEN_MISMATCH]: { statusCode: 404, message: "refresh 토큰이 일치하지 않습니다." },
  [BusinessExceptionType.EMAIL_TOO_LONG]: { statusCode: 404, message: "이메일이 너무 깁니다." },
  [BusinessExceptionType.PASSWORD_TOO_SHORT]: { statusCode: 404, message: "비밀번호가 너무 짧습니다." },
  [BusinessExceptionType.NICKNAME_TOO_LONG]: { statusCode: 404, message: "닉네임이 너무 깁니다." },
  [BusinessExceptionType.ZOD_FORM]: { statusCode: 400, message: "잘못된 요청 형식입니다." },
  [BusinessExceptionType.NAME_NOT_EXIST]: { statusCode: 400, message: "이름은 입력하지 않았습니다.(필수)" },
  [BusinessExceptionType.DESCRIPTION_NOT_EXIST]: { statusCode: 400, message: "설명을 입력하지 않았습니다.(필수)" },
  [BusinessExceptionType.PRICE_NOT_EXIST]: { statusCode: 400, message: "가격은 입력하지 않았습니다.(필수)" },
  [BusinessExceptionType.TAGS_NOT_EXIST]: { statusCode: 400, message: "태그를 입력하지 않았습니다.(필수)" },
  [BusinessExceptionType.TITLE_NOT_EXIST]: { statusCode: 404, message: "제목이 존재하지 않습니다." },
  [BusinessExceptionType.CONTENT_NOT_EXIST]: { statusCode: 404, message: "내용이 존재하지 않습니다." },
  [BusinessExceptionType.ARTICLE_NOT_EXIST]: { statusCode: 404, message: "게시글이 존재하지 않습니다." },
  [BusinessExceptionType.COMMENT_NOT_EXIST]: { statusCode: 404, message: "댓글이 존재하지 않습니다." },
  [BusinessExceptionType.PRODUCT_NOT_EXIST]: { statusCode: 404, message: "상품이 존재하지 않습니다." },
  [BusinessExceptionType.NOTIFICATION_NOT_EXIST]: { statusCode: 404, message: "알림이 존재하지 않습니다." },
  [BusinessExceptionType.LIKE_NOT_EXIST]: { statusCode: 404, message: "이미 좋아요가 안 눌러져 있습니다." },
  [BusinessExceptionType.LIKE_EXIST]: { statusCode: 404, message: "이미 좋아요가 눌러져 있습니다." },
  [BusinessExceptionType.ID_NOT_EXIST]: { statusCode: 404, message: "id가 존재하지 않습니다." },
  [BusinessExceptionType.TARGETTYPE_NOT_EXIST]: { statusCode: 404, message: "타겟 타입이 존재하지 않습니다." },
  [BusinessExceptionType.USER_NOT_EXIST]: { statusCode: 404, message: "유저가 존재하지 않습니다." },
  [BusinessExceptionType.USER_PRODUCTS_NOT_EXIST]: { statusCode: 404, message: "유저의 상품이 존재하지 않습니다." },
  [BusinessExceptionType.USER_LIKEPRODUCTS_NOT_EXIST]: { statusCode: 404, message: "유저의 좋아요 상품이 존재하지 않습니다." },
  [BusinessExceptionType.USER_LIKEARTICLES_NOT_EXIST]: { statusCode: 404, message: "유저의 좋아요 게시글이 존재하지 않습니다." },
  [BusinessExceptionType.REFRESHTOKEN_NOT_EXIST]: { statusCode: 404, message: "refresh 토큰이 존재하지 않습니다." },
  [BusinessExceptionType.USERID_NOT_EXIST]: { statusCode: 404, message: "userId가 없습니다." },
  [BusinessExceptionType.PRODUCT_ALREADY_EXIST]: { statusCode: 409, message: "이미 상품이 존재합니다." },
  [BusinessExceptionType.ARTICLE_ALREADY_EXIST]: { statusCode: 409, message: "이미 게시글이 존재합니다." },
  [BusinessExceptionType.COMMENT_ALREADY_EXIST]: { statusCode: 409, message: "이미 댓글이 존재합니다." },
  [BusinessExceptionType.EMAIL_DUPLICATE]: { statusCode: 409, message: "중복된 이름입니다." },
  [BusinessExceptionType.FOREIGN_KEY_VIOLATION]: { statusCode: 422, message: "존재하지 않은 외래키입니다." },
  [BusinessExceptionType.USER_EXIST]: { statusCode: 409, message: "이미 유저가 존재합니다." },
  [BusinessExceptionType.UNAUTHORIZED_PRODUCT_OWNER]: { statusCode: 403, message: "해당 상품에 대한 권한이 없습니다." },
  [BusinessExceptionType.UNAUTHORIZED_ARTICLE_OWNER]: { statusCode: 403, message: "해당 게시글에 대한 권한이 없습니다." },
  [BusinessExceptionType.UNAUTHORIZED_COMMENT_OWNER]: { statusCode: 403, message: "해당 댓글에 대한 권한이 없습니다." },
  [BusinessExceptionType.CORS_ORIGIN_NOT_ALLOWED]: { statusCode: 403, message: "허용되지 않은 도메인으로 연결을 시도했습니다." },
  [BusinessExceptionType.INVALID_TOKEN]: { statusCode: 404, message: "토큰이 유효하지 않습니다." },
  [BusinessExceptionType.NOT_PATH]: { statusCode: 404, message: "알 수 없는 url 경로입니다." },
};
