# Github Secrets
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_REGION
# ECR_SERVER_URI
# EC2_HOST
# EC2_USERNAME
# EC2_SSH_PRIVATE_KEY
# ENV

name: ci/cd

on:
  pull_request:
    branches: ["정인성-sprint11"]
  push:
    branches: ["main", "정인성-sprint11"]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: install dependencies
        run: npm ci
      
      - name: create .env.test
        run: |
          echo "${{ secrets.ENV_TEST }}" > .env.test
      
      - name: prisma generate
        run: npx prisma generate

      - name: check types
        run: npm run type:check

      - name: check format
        run: npm run format:check
      
      - name: run unit test
        run: npm run test:all

  